package com.ade.exp.cayenne.base.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.ade.exp.cayenne.base.persistent.Company;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ADDRESS = Property.create("address", String.class);
    public static final Property<Integer> AGE = Property.create("age", Integer.class);
    public static final Property<String> EMAIL = Property.create("email", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<Company> COMPANY = Property.create("company", Company.class);

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setAge(Integer age) {
        writeProperty("age", age);
    }
    public Integer getAge() {
        return (Integer)readProperty("age");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setCompany(Company company) {
        setToOneTarget("company", company, true);
    }

    public Company getCompany() {
        return (Company)readProperty("company");
    }


}
